name: Build and Deploy Vlocity Components to Dev Org

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.12.2'

    - name: Install Salesforce CLI
      run: |
        npm install -g @salesforce/cli
        echo "::add-path::$(npm bin -g)"

    - name: Authenticate to Salesforce
      env:
        SF_AUTOUPDATE_DISABLE: 'true'
        SFDX_CLIENT_ID: ${{ secrets.SFDX_CLIENT_ID }}
        SFDX_USERNAME: ${{ secrets.SFDX_USERNAME }}
        SFDX_LOGIN_URL: ${{ secrets.SFDX_LOGIN_URL }}
      run: |
        sf auth:jwt:grant --clientid $SFDX_CLIENT_ID --jwtkeyfile server.key --username $SFDX_USERNAME --setdefaultdevhubusername --setalias my-dev-org --instanceurl $SFDX_LOGIN_URL
