name: Salesforce JWT Auth

on:
  push:
    branches:
      - main

jobs:
  authenticate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Salesforce CLI
        run: |
          npm install -g sfdx-cli

      - name: Create JWT key
        run: |
          openssl genrsa -out server.key 2048
          openssl req -new -key server.key -out server.csr -subj "/CN=Salesforce"
          openssl x509 -req -days 365 -in server.csr -signkey server.key -out server.crt

      - name: Create Connected App
        run: |
          sfdx force:auth:jwt:grant --clientid ${{ secrets.SFDX_CLIENT_ID }} --jwtkeyfile server.key --username ${{ secrets.SFDX_USERNAME }} --setdefaultdevhubusername --setalias my-dev-org --instanceurl ${{ secrets.SFDX_LOGIN_URL }}

      - name: Use JWT Key
        run: |
          echo "JWT_SECRET=$JWT_SECRET" >> $GITHUB_ENV
