projectPath: VlocityCard/VlocityCard/test2/VlocityCard/test2
Name: manage component
ignoreDependencies: false
VlocityDataPackKeys:
    - VlocityCard
VlocityTypesToFetch:
    - VlocityCard
SalesforceTypesToFetch:
