name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install OpenSSL
        run: sudo apt-get install -y openssl

      - name: Generate server.key
        run: |
          openssl genrsa -out server.key 2048
          openssl req -new -key server.key -out server.csr -subj "/CN=Salesforce"
          openssl x509 -req -days 365 -in server.csr -signkey server.key -out server.crt
          cat server.key

      - name: Set JWT environment variable
        run: echo "JWT_SECRET=$JWT_SECRET" >> $GITHUB_ENV
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      - name: Install Salesforce CLI
        run: |
          npm install -g @salesforce/cli
          echo 'export PATH="$PATH:$(npm prefix -g)/bin"' >> $GITHUB_ENV

      - name: Authenticate to Salesforce
        run: |
          sf auth:jwt:grant --client-id PlatformCLI --jwt-key-file server.key --username kumar@sentara.sandbox --set-default-dev-hub --alias vscodeOrg --instance-url https://bermtecinc-dev-ed.develop.my.salesforce.com
