name: Build and Deploy Vlocity Components to Dev Org

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Salesforce CLI
        uses: sfdx-actions/setup-sfdx@v1
      
      - name: Install dependencies
        run: npm install -g vlocity

      - name: Build project
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ success() }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Salesforce CLI
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-linux-x64.tar.xz
          mkdir -p ~/cli/sf
          tar xJf sf-linux-x64.tar.xz -C ~/cli/sf --strip-components 1
          export PATH=~/cli/sf/bin:$PATH
          sf --version

      - name: Authenticate with Salesforce Dev Org
        env:
          SFDX_LOGIN_URL: ${{ secrets.SFDX_LOGIN_URL }}
          SFDX_USERNAME: ${{ secrets.SFDX_USERNAME }}
          SFDX_CLIENT_ID: ${{ secrets.SFDX_CLIENT_ID }}
          SFDX_CLIENT_SECRET: ${{ secrets.SFDX_CLIENT_SECRET }}
          SFDX_JWT_KEY_FILE: ${{ secrets.SFDX_JWT_KEY_FILE }}
        run: |
          export PATH=~/cli/sf/bin:$PATH
          sf org login jwt --client-id $SFDX_CLIENT_ID --jwt-key-file $SFDX_JWT_KEY_FILE --username $SFDX_USERNAME --instance-url $SFDX_LOGIN_URL --set-default-dev-hub --alias my-dev-org

      - name: Deploy Vlocity Components
        env:
          SFDX_PACKAGE_PATH: 'path/to/your/vlocity/package'
        run: |
          export PATH=~/cli/sf/bin:$PATH
          sf deploy metadata --source-path $SFDX_PACKAGE_PATH --target-org my-dev-org
