name: Build and Deploy Vlocity Components to Dev Org

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Salesforce CLI
        uses: sfdx-actions/setup-sfdx@v1
      
      - name: Install dependencies
        run: npm install -g vlocity

      - name: Build project
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ success() }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Salesforce CLI
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-linux-x64.tar.xz
          mkdir -p ~/cli/sf
          tar xJf sf-linux-x64.tar.xz -C ~/cli/sf --strip-components 1
          export PATH=~/cli/sf/bin:$PATH
          sf --version

      - name: Authenticate with Salesforce Dev Org
        env:
          SFDX_LOGIN_URL: https://saforceit6-dev-ed.develop.my.salesforce.com/
          SFDX_USERNAME: sam.nathan3699@devops.com
          SFDX_CLIENT_ID: 3MVG9JJwBBbcN47LO.vTT_CuU2g_gOobvkFW3lcm5J9OhnKThVjeErP8nFpqlUBHxU4E6zhW86Kv.MLKY.XPE
          SFDX_CLIENT_SECRET: 6Cel800Dak000002ErMl888ak00000025ur4jIfzL90LirG8A6WrzdodLI3s7CGXJ66BntooLh64jRlLIVly92lhpOddyGwTGCFgwJp8q30
          SFDX_JWT_KEY_FILE: 4CC66C0DD74D330BA64DE24245C5F6995A902E47E0BA75F473DBE3C7C0A36CE5
        run: |
          export PATH=~/cli/sf/bin:$PATH
          sf org login jwt --client-id $SFDX_CLIENT_ID --jwt-key-file $SFDX_JWT_KEY_FILE --username $SFDX_USERNAME --instance-url $SFDX_LOGIN_URL --set-default-dev-hub --alias my-dev-org

      - name: Deploy Vlocity Components
        env:
          SFDX_PACKAGE_PATH: 'path/to/your/vlocity/package'
        run: |
          export PATH=~/cli/sf/bin:$PATH
          sf deploy metadata --source-path $SFDX_PACKAGE_PATH --target-org my-dev-org
