jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Specify the Node.js version

      # Install Vlocity Build Tool
      - name: Install Vlocity Build Tool
        run: |
          # Install the Vlocity Build Tool globally
          npm install -g vlocity

      # Verify installation and install application dependencies
      - name: Verify Vlocity Build Tool installation and install dependencies
        run: |
          # Verify installation of vlocity-build
          if ! command -v vlocity-build &> /dev/null; then
            echo "Failed to install or find vlocity-build."
            exit 1
          fi

          # Install other application dependencies
          npm install
