name: Build Salesforce App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Linting
        run: |
          npm run lint
          npm run prettier:verify

      - name: Building project
        run: npm run build

      - name: Running unit tests
        run: npm run test
