name: build

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      
      - name: Install Vlocity Build
        run: npm install -g git+https://github.com/VlocityCard/test2.git

