name: Build 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Salesforce CLI
        uses: sfdx-actions/setup-sfdx@v1
      
      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        
  # Create and publish artifact (e.g., Docker image)
      - name: Create and publish Docker image
        run: |
          # Create the Docker image
          docker build -t vlocity-artifact .

      # Tag the artifact
      - name: Tag Docker image
        run: |
          # Tag the Docker image
          docker tag vlocity-artifact ${ACR_URL}/vlocity-artifact:latest
