name: Build 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Salesforce CLI
        uses: sfdx-actions/setup-sfdx@v1
      
      - name: Install dependencies
        run: npm install –global vlocity

      - name: Build project
        run: npm run build 
        
      # Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: vlocity-build-artifact
          path: .github/workflows


    name: CD Deploy to Salesforce DevOps Center Evn 

