name: Vlocity Build


on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Install PMD
      - name: 'Install PMD'
        run: |
            PMD_VERSION=`cat pmd/pmd-version.txt`
            wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F$PMD_VERSION/pmd-bin-$PMD_VERSION.zip
            unzip pmd-bin-$PMD_VERSION.zip -d ~
            mv ~/pmd-bin-$PMD_VERSION ~/pmd
            ~/pmd/bin/run.sh pmd --version
            # Run PMD scan
      - name: 'Run PMD scan'
        run: ~/pmd/bin/run.sh pmd -d force-app -R pmd/ruleset.xml -f text
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Salesforce CLI
        uses: sfdx-actions/setup-sfdx@v1
      
      - name: Install dependencies
        run: npm install -g vlocity

      - name: Build project
        run: npm run build 
        
      # Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: vlocity-build-artifact
          path: .github/workflows


   

